#! /bin/sh

sxhkd &
polybar -c ~/.config/polybar/config.amber main &
dunst &

#jackd --silent -d alsa -d hw:1
feh --no-fehbg --bg-scale '/home/drslowpokephd/Dotfiles/.wallpapers/landscape.png'

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12
bspc config active_border_color "#fbf1c7"
bspc config single_monocle true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Unity state=floating
# bspc rule -a scratchpad sticky=on state=floating hidden=on
# st -c scratchpad -e ~/bin/scratch &
# id=$(cat /tmp/scratchid);\
# bspc node $id --flag hidden;bspc node -f $id
