#! /bin/sh

sxhkd &
polybar -c ~/.config/polybar/config.amber &

#jackd --silent -d alsa -d hw:1
~/Dotfiles/.fehbg 

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Unity state=floating
# bspc rule -a scratchpad sticky=on state=floating hidden=on
# st -c scratchpad -e ~/bin/scratch &
# id=$(cat /tmp/scratchid);\
# bspc node $id --flag hidden;bspc node -f $id
