#! /bin/sh

sxhkd &
# killall polybar &
polybar -c ~/.config/polybar/config.amber main &
dunst -conf ~/.config/dunst/dunstrc &

#jackd --silent -d alsa -d hw:1
feh --no-fehbg --bg-scale '/home/drslowpokephd/Dotfiles/.wallpapers/landscape.png'

bspc monitor -d I II III IV V

bspc config border_width         6 
bspc config window_gap          20
bspc config focused_border_color "#d79921"
bspc config normal_border_color "#282828"
bspc config single_monocle true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Unity state=floating
# bspc rule -a scratchpad sticky=on state=floating hidden=on
# st -c scratchpad -e ~/bin/scratch &
# id=$(cat /tmp/scratchid);\
# bspc node $id --flag hidden;bspc node -f $id
